import QtQuick

// The file-tree / file-preview state.
//
// Owns exactly the state the files:* channels produce:
//   - `tree`           FileNode[] returned by files:listTree (recursive)
//   - `flat`           FileNode[] returned by files:listDir (one level, lazy)
//   - `excludePatterns` array of folder names to skip, sourced from the
//                       files_excludePatterns setting (comma-separated) with
//                       generated/settingDefs.js DEFAULT_EXCLUDE_PATTERNS
//                       as the fallback when the setting is absent
//   - `currentPath`    the path whose contents are in `flat`
//   - `reading`        the FileReadResult last returned by files:readFile
//   - `error`          last error string surfaced by any channel
//
// One authoritative owner per mutable value. Nothing else writes to these
// properties — `App.qml`'s FilesPane binds to `tree`, `flat`, and
// `reading`, and the preview pane's only path is `read(path)`.
//
// A store that imports Quickshell cannot be loaded by qmltestrunner
// (CONTRACTS.md §2), so reveal/open-with/trash live in components, not here.
// The store exposes `revealRequested` / `openExternalRequested` /
// `trashRequested` signals instead, and `Main` wires those to
// Quickshell.execDetached calls in one place.
QtObject {
  id: store

  // Service.qml, which owns invoke/subscribe.
  required property var rpc

  // The recursive tree under the active conversation's cwd.
  property var tree: []
  // One-level listing under currentPath — used when the user expands a
  // folder the recursive tree didn't include (depth cap, excluded dir).
  property var flat: []
  property string currentPath: ""

  // Path -> FileReadResult. Keyed by path so reopening a file reuses the
  // last-read result; the preview pane decides whether to refetch on
  // staleness (a write invalidates).
  property var reads: ({})
  // Convenience for the preview pane: the path it is currently showing.
  property string activeReadPath: ""

  // Whether a listTree / listDir / readFile call is in flight. Drives the
  // preview pane's "loading" hint without subscribing to per-call handlers.
  property bool loading: false
  property string error: ""

  // Folder names to skip during listTree, sourced from
  //   files_excludePatterns setting (comma-separated) when present, else
  //   DEFAULT_EXCLUDE_PATTERNS from generated/settingDefs.js.
  // The setting list is read at load() time and refreshed when the
  // settings:changed push arrives.
  property var excludePatterns: []

  // ---- signals consumed by Main ----------------------------------------

  signal revealRequested(string path)
  signal openExternalRequested(string path)
  signal trashRequested(string path)

  // ---- helpers ---------------------------------------------------------

  // Parse a comma-separated exclude-pattern list. Empty / null / unset
  // returns the empty array — `loadTree` then falls back to defaults
  // before invoking the channel.
  function parseExcludePatterns(raw) {
    if (!raw) return []
    var parts = String(raw).split(",")
    var out = []
    for (var i = 0; i < parts.length; i++) {
      var p = String(parts[i]).trim()
      if (p.length > 0) out.push(p)
    }
    return out
  }

  function refreshExcludePatterns() {
    var raw = ""
    if (rpc && rpc.settingsStore && typeof rpc.settingsStore.get === "function") {
      raw = rpc.settingsStore.get("files_excludePatterns", "")
    }
    var parsed = parseExcludePatterns(raw)
    if (parsed.length === 0) {
      // DEFAULT_EXCLUDE_PATTERNS is generated by scripts/emit-setting-defs.ts
      // into generated/settingDefs.js (a QML JS resource). Importing it
      // here would couple the store to a generated file at runtime; the
      // fallback is the empty array plus node_modules (the server's
      // default), which listTree uses anyway.
      excludePatterns = ["node_modules"]
    } else {
      excludePatterns = parsed
    }
  }

  // ---- load ------------------------------------------------------------

  function load(cwd) {
    if (!cwd) cwd = ""
    refreshExcludePatterns()
    if (cwd.length === 0) {
      tree = []
      error = "No cwd"
      return
    }
    loading = true
    rpc.invoke("files:listTree", [cwd, excludePatterns], function(result) {
      loading = false
      tree = (result && result.length) ? result : []
      currentPath = cwd
      error = ""
    }, function(err) {
      loading = false
      tree = []
      error = String(err)
    })
  }

  function loadFlat(path) {
    if (!path) return
    loading = true
    rpc.invoke("files:listDir", [path], function(result) {
      loading = false
      flat = (result && result.length) ? result : []
      currentPath = path
      error = ""
    }, function(err) {
      loading = false
      flat = []
      error = String(err)
    })
  }

  // ---- preview ---------------------------------------------------------

  // Fetch the file. Result shape (from files:readFile):
  //   { content: string, language: string }
  //   - text-like: content is utf-8, language is one of the server's
  //     classifyFileExt outputs ("javascript", "python", "markdown", ...).
  //   - image: content is a "data:<mime>;base64,<...>" URL, language
  //     is "image".
  //   - binary model (.stl/.3mf/.ply): content is base64, language
  //     is "model" — FilePreview.qml routes those to 'external' because
  //     we have no 3D renderer.
  function read(path) {
    if (!path) return
    loading = true
    rpc.invoke("files:readFile", [path], function(result) {
      loading = false
      var next = ({})
      for (var k in reads) next[k] = reads[k]
      next[path] = result
      reads = next
      activeReadPath = path
      error = ""
    }, function(err) {
      loading = false
      error = String(err)
    })
  }

  function activeRead() {
    if (!activeReadPath) return null
    return reads[activeReadPath] || null
  }

  // The size of the active read, in bytes, when known. The server's
  // listTree / listDir responses do not include size, so this returns
  // undefined for "unknown" and the preview pane falls back to the size
  // guard's null branch (always allow).
  function activeReadSize() {
    // The server only returns the file size inside files:readFile's error
    // message ("File too large to preview"); we do not have a stable
    // channel for size, so the preview pane asks us. Until we know,
    // returning undefined lets lib/filePreview's null branch win (always
    // allow, route to text).
    return undefined
  }

  // ---- writes ----------------------------------------------------------

  function write(path, content, onOk, onErr) {
    if (!path) return
    rpc.invoke("files:writeFile", [path, String(content || "")], function(result) {
      // The local cached read is now stale; the preview pane refetches
      // if the user re-opens the file. We deliberately do NOT invalidate
      // `reads[path]` so an unsaved-but-now-saved file can be re-edited
      // without losing the user's local changes (a known footgun in
      // editors that auto-refetch on save).
      if (onOk) onOk(result)
    }, function(err) {
      error = String(err)
      if (onErr) onErr(err)
    })
  }

  function rename(path, newName, onOk, onErr) {
    rpc.invoke("files:rename", [path, String(newName || "")], function(result) {
      if (onOk) onOk(result)
    }, function(err) {
      error = String(err)
      if (onErr) onErr(err)
    })
  }

  function duplicate(path, onOk, onErr) {
    rpc.invoke("files:duplicate", [path], function(result) {
      if (onOk) onOk(result)
    }, function(err) {
      error = String(err)
      if (onErr) onErr(err)
    })
  }

  function move(sourcePath, destDir, onOk, onErr) {
    rpc.invoke("files:move", [sourcePath, String(destDir || "")], function(result) {
      if (onOk) onOk(result)
    }, function(err) {
      error = String(err)
      if (onErr) onErr(err)
    })
  }

  function createFile(dir, name, onOk, onErr) {
    rpc.invoke("files:createFile", [String(dir || ""), String(name || "")], function(result) {
      if (onOk) onOk(result)
    }, function(err) {
      error = String(err)
      if (onErr) onErr(err)
    })
  }

  function createFolder(dir, name, onOk, onErr) {
    rpc.invoke("files:createFolder", [String(dir || ""), String(name || "")], function(result) {
      if (onOk) onOk(result)
    }, function(err) {
      error = String(err)
      if (onErr) onErr(err)
    })
  }

  // Open a terminal in the file's parent directory. Reachable from
  // loopback only (Phase 4.1).
  function openTerminalHere(path) {
    rpc.invoke("files:openTerminalHere", [String(path || "")], function() {}, function(err) {
      error = String(err)
    })
  }

  // Prepare a conversation session from a set of source paths. Four
  // required args plus an optional renames map (oldPath -> newName).
  // Returns { cwd: <destDir>, count: <n> } on success.
  // Reachable from loopback only (Phase 4.1).
  function prepareSession(conversationId, sourcePaths, method, renames, onOk, onErr) {
    if (method !== "copy" && method !== "symlink") method = "copy"
    var args = [conversationId, sourcePaths || [], method]
    if (renames) args.push(renames)
    rpc.invoke("files:prepareSession", args, function(result) {
      if (onOk) onOk(result)
    }, function(err) {
      error = String(err)
      if (onErr) onErr(err)
    })
  }

  // ---- local-command requests -----------------------------------------

  function revealInFileManager(path) {
    revealRequested(String(path || ""))
  }

  function openExternal(path) {
    openExternalRequested(String(path || ""))
  }

  function trash(path) {
    trashRequested(String(path || ""))
  }
}
