// Emits the settings constants the Omarchy QML plugin needs as one plain ES
// module, so the plugin reads the same data the React settings page does
// instead of carrying a hand-copied duplicate that silently drifts.
//
// Run through `npm run build:omarchy-consts`, which bundles this with esbuild
// and pipes stdout into omarchy/plugins/agent-desktop/generated/settingDefs.js.
// stdout carries the module and nothing else — every diagnostic goes to stderr.
import {
  SETTING_DEFS,
  AI_OVERRIDE_KEYS,
  PERMISSION_OPTIONS,
  SDK_BACKEND_OPTIONS,
  SETTING_SOURCES_OPTIONS,
  CONFIG_SHARING_OPTIONS,
  SKILLS_TOGGLE_OPTIONS,
  PLAN_APPROVAL_OPTIONS,
  MODEL_OPTIONS,
  DEFAULT_MODEL,
  BACKEND_DISPLAY_NAMES,
  NOTIFICATION_EVENTS,
  DEFAULT_NOTIFICATION_CONFIG,
  DEFAULT_EXCLUDE_PATTERNS,
  WS_DISCONNECTED_MESSAGE,
} from '../src/core/types/constants'

const EXPORTS: Record<string, unknown> = {
  SETTING_DEFS,
  AI_OVERRIDE_KEYS,
  PERMISSION_OPTIONS,
  SDK_BACKEND_OPTIONS,
  SETTING_SOURCES_OPTIONS,
  CONFIG_SHARING_OPTIONS,
  SKILLS_TOGGLE_OPTIONS,
  PLAN_APPROVAL_OPTIONS,
  MODEL_OPTIONS,
  DEFAULT_MODEL,
  BACKEND_DISPLAY_NAMES,
  NOTIFICATION_EVENTS,
  DEFAULT_NOTIFICATION_CONFIG,
  DEFAULT_EXCLUDE_PATTERNS,
  WS_DISCONNECTED_MESSAGE,
}

// The output is a QML JS *resource*, not an ES module: `.pragma library` plus
// top-level `var` declarations, which is the only shape `import "…" as Consts`
// can consume. Node tests read the same file through tests/load.js, so both
// engines see the identical bytes.
const lines: string[] = [
  '.pragma library',
  '',
  '// GENERATED by scripts/emit-setting-defs.ts — do not edit.',
  '// Regenerate with: npm run build:omarchy-consts',
  '//',
  '// The source of truth is src/core/types/constants.ts. This file exists so the',
  '// QML settings page can be generated from the same data the React one is,',
  '// rather than from a hand-copied duplicate that drifts.',
  '',
]

for (const [name, value] of Object.entries(EXPORTS)) {
  lines.push(`var ${name} = ${JSON.stringify(value, null, 2)}`)
  lines.push('')
}

process.stdout.write(lines.join('\n'))
