// GENERATED by tests/gen-stubs.js from /usr/share/omarchy/shell/Ui/BarWidget.qml — do not edit.
//
// Offscreen stand-in so the QML suite runs with no shell. Only the root
// object's declaration NAMES matter; the bodies are deliberately empty.
// Regenerate with: node tests/gen-stubs.js

import QtQuick

Item {
  property QtObject bar: null
  property string moduleName: ""
  property var settings: undefined
  property bool vertical: false
  property int barSize: 0
  function broadcast(method) { return undefined }
  function setting(name, fallback) { return undefined }

  implicitWidth: 120
  implicitHeight: 28
}
