// GENERATED by tests/gen-stubs.js from /usr/share/omarchy/shell/Ui/BorderSurface.qml — do not edit.
//
// Offscreen stand-in so the QML suite runs with no shell. Only the root
// object's declaration NAMES matter; the bodies are deliberately empty.
// Regenerate with: node tests/gen-stubs.js

import QtQuick

Rectangle {
  property var borderSpec: undefined
  property real padding: 0
  property real topPadding: 0
  property real rightPadding: 0
  property real bottomPadding: 0
  property real leftPadding: 0
  property real borderTop: 0
  property real borderRight: 0
  property real borderBottom: 0
  property real borderLeft: 0
  property real contentTopInset: 0
  property real contentRightInset: 0
  property real contentBottomInset: 0
  property real contentLeftInset: 0
  property bool usesOverlayBorder: false
}
