// GENERATED by tests/gen-stubs.js from /usr/share/omarchy/shell/Ui/Button.qml — do not edit.
//
// Offscreen stand-in so the QML suite runs with no shell. Only the root
// object's declaration NAMES matter; the bodies are deliberately empty.
// Regenerate with: node tests/gen-stubs.js

import QtQuick

Item {
  property string text: ""
  property string iconText: ""
  property string tooltipText: ""
  property bool selected: false
  property bool active: false
  property bool hasCursor: false
  property bool focusable: false
  property bool bordered: false
  property color foreground: "transparent"
  property color background: "transparent"
  property color accent: "transparent"
  property string fontFamily: ""
  property real fontSize: 0
  property real iconSize: 0
  property real iconRotation: 0
  property bool iconSpinning: false
  property real horizontalPadding: 0
  property real verticalPadding: 0
  property bool leftAlign: false
  property color tooltipBackground: "transparent"
  property color tooltipForeground: "transparent"
  property color tooltipBorder: "transparent"
  signal clicked()
  signal rightClicked()
  signal hovered(bool isHovered)
  property bool hot: false

  implicitWidth: 120
  implicitHeight: 28
}
