// GENERATED by tests/gen-stubs.js from /usr/share/omarchy/shell/Ui/ConfirmDialog.qml — do not edit.
//
// Offscreen stand-in so the QML suite runs with no shell. Only the root
// object's declaration NAMES matter; the bodies are deliberately empty.
// Regenerate with: node tests/gen-stubs.js

import QtQuick

Item {
  property bool opened: false
  property string message: ""
  property string cancelText: ""
  property string confirmText: ""
  property int selectedIndex: 0
  property color background: "transparent"
  property color foreground: "transparent"
  property color scrim: "transparent"
  property color selectedBackground: "transparent"
  property color selectedText: "transparent"
  property string fontFamily: ""
  property int cornerRadius: 0
  signal canceled()
  signal confirmed()
  function handleKey(event) { return undefined }

  implicitWidth: 120
  implicitHeight: 28
}
