// GENERATED by tests/gen-stubs.js from /usr/share/omarchy/shell/Ui/Dropdown.qml — do not edit.
//
// Offscreen stand-in so the QML suite runs with no shell. Only the root
// object's declaration NAMES matter; the bodies are deliberately empty.
// Regenerate with: node tests/gen-stubs.js

import QtQuick

Item {
  property string label: ""
  property string value: ""
  property var options: undefined
  property color foreground: "transparent"
  property color background: "transparent"
  property color popupBorder: "transparent"
  property color accent: "transparent"
  property var popupBorderSpec: undefined
  property string fontFamily: ""
  property int rowHeight: 0
  property int popupRowHeight: 0
  property bool showLabel: false
  property bool hasCursor: false
  property bool popupOpen: false
  function open() { return undefined }
  function close() { return undefined }
  function toggle() { return undefined }
  signal changed(string value)
  signal hovered(bool isHovered)
  function optionValue(o) { return undefined }
  function optionLabel(o) { return undefined }
  function currentLabel() { return undefined }

  implicitWidth: 120
  implicitHeight: 28
}
