// GENERATED by tests/gen-stubs.js from /usr/share/omarchy/shell/Ui/MultiSelect.qml — do not edit.
//
// Offscreen stand-in so the QML suite runs with no shell. Only the root
// object's declaration NAMES matter; the bodies are deliberately empty.
// Regenerate with: node tests/gen-stubs.js

import QtQuick

Item {
  property string label: ""
  property var values: undefined
  property var options: undefined
  property var optionsCommand: undefined
  property string optionsCommandCwd: ""
  property string placeholderText: ""
  property string emptyText: ""
  property string noSelectionText: ""
  property string triggerLabel: ""
  property bool showLabel: false
  property color foreground: "transparent"
  property color background: "transparent"
  property color popupBorder: "transparent"
  property color accent: "transparent"
  property var popupBorderSpec: undefined
  property string fontFamily: ""
  property int rowHeight: 0
  property int popupRowHeight: 0
  property int popupMinHeight: 0
  property bool hasCursor: false
  property bool popupOpen: false
  function open() { return undefined }
  function close() { return undefined }
  function toggle() { return undefined }
  signal changed(var values)
  signal hovered(bool isHovered)
  property var resolvedOptions: undefined
  property bool loadingOptions: false
  property string optionsError: ""
  function normalizeOption(o) { return undefined }
  function arrayFrom(v) { return undefined }
  function normalizeAll(arr) { return undefined }
  function valueSet() { return undefined }
  function isSelected(value) { return undefined }
  function toggleValue(value) { return undefined }
  function selectionLabel() { return undefined }
  property var filtered: undefined
  function recomputeFiltered() { return undefined }
  function rebuildFromStatic() { return undefined }
  function parseCommandOutput(text) { return undefined }
  property int refreshSeq: 0
  property int refreshTimeoutMs: 0
  function refresh() { return undefined }

  implicitWidth: 120
  implicitHeight: 28
}
