// GENERATED by tests/gen-stubs.js from /usr/share/omarchy/shell/Ui/NumberField.qml — do not edit.
//
// Offscreen stand-in so the QML suite runs with no shell. Only the root
// object's declaration NAMES matter; the bodies are deliberately empty.
// Regenerate with: node tests/gen-stubs.js

import QtQuick

Item {
  property string label: ""
  property int value: 0
  property int from: 0
  property int to: 0
  property int stepSize: 0
  property color foreground: "transparent"
  property color accent: "transparent"
  property string fontFamily: ""
  property real fontSize: 0
  property real fieldWidth: 0
  property bool hasCursor: false
  signal modified(int value)
  signal hovered(bool on)

  implicitWidth: 120
  implicitHeight: 28
}
