// GENERATED by tests/gen-stubs.js from /usr/share/omarchy/shell/Ui/OpticalGlyph.qml — do not edit.
//
// Offscreen stand-in so the QML suite runs with no shell. Only the root
// object's declaration NAMES matter; the bodies are deliberately empty.
// Regenerate with: node tests/gen-stubs.js

import QtQuick

Text {
  property string fontFamily: ""
  property real fontSize: 0
  property bool debugBounds: false
  property int renderedFontSize: 0
  property real tightWidth: 0
  property real horizontalCorrection: 0
  property real paintedCenterX: 0
  property real baselineY: 0
}
