// GENERATED by tests/gen-stubs.js from /usr/share/omarchy/shell/Ui/PanelSeparator.qml — do not edit.
//
// Offscreen stand-in so the QML suite runs with no shell. Only the root
// object's declaration NAMES matter; the bodies are deliberately empty.
// Regenerate with: node tests/gen-stubs.js

import QtQuick

Item {
  property color foreground: "transparent"
  property real strength: 0

  implicitWidth: 120
  implicitHeight: 28
}
