// GENERATED by tests/gen-stubs.js from /usr/share/omarchy/shell/Ui/PanelToolTip.qml — do not edit.
//
// Offscreen stand-in so the QML suite runs with no shell. Only the root
// object's declaration NAMES matter; the bodies are deliberately empty.
// Regenerate with: node tests/gen-stubs.js

import QtQuick

Item {
  property color panelForeground: "transparent"
  property color panelBackground: "transparent"
  property color panelBorder: "transparent"
  property string fontFamily: ""
  property real fontSize: 0
  property var panelBorderSpec: undefined

  implicitWidth: 120
  implicitHeight: 28
}
