// GENERATED by tests/gen-stubs.js from /usr/share/omarchy/shell/Ui/PanelSlider.qml — do not edit.
//
// Offscreen stand-in so the QML suite runs with no shell. Only the root
// object's declaration NAMES matter; the bodies are deliberately empty.
// Regenerate with: node tests/gen-stubs.js

import QtQuick

Item {
  property QtObject bar: null
  property real value: 0
  property real minimum: 0
  property real maximum: 0
  property real step: 0
  property bool integer: false
  property color trackColor: "transparent"
  property color fillColor: "transparent"
  property color knobColor: "transparent"
  property bool dragging: false
  property real trackHeight: 0
  property real knobSize: 0
  property real liveValue: 0
  property int tickCount: 0
  property color tickColor: "transparent"
  signal moved(real value)
  signal released(real value)
  signal rightClicked()
  property real range: 0
  property real progress: 0

  implicitWidth: 120
  implicitHeight: 28
}
