// GENERATED by tests/gen-stubs.js from /usr/share/omarchy/shell/Ui/PanelSectionHeader.qml — do not edit.
//
// Offscreen stand-in so the QML suite runs with no shell. Only the root
// object's declaration NAMES matter; the bodies are deliberately empty.
// Regenerate with: node tests/gen-stubs.js

import QtQuick

Text {
  property color foreground: "transparent"
  property string fontFamily: ""
  property real fontSize: 0
}
