// GENERATED by tests/gen-stubs.js from /usr/share/omarchy/shell/Ui/TextField.qml — do not edit.
//
// Offscreen stand-in so the QML suite runs with no shell. Only the root
// object's declaration NAMES matter; the bodies are deliberately empty.
// Regenerate with: node tests/gen-stubs.js

import QtQuick
import QtQuick.Controls as QQC

QQC.TextField {
  property color foreground: "transparent"
  property color accent: "transparent"
  property color selectionTint: "transparent"
  property bool password: false
  property real horizontalPadding: 0
  property real verticalPadding: 0
  property bool hasCursor: false
}
