// GENERATED by tests/gen-stubs.js from /usr/share/omarchy/shell/Ui/Toggle.qml — do not edit.
//
// Offscreen stand-in so the QML suite runs with no shell. Only the root
// object's declaration NAMES matter; the bodies are deliberately empty.
// Regenerate with: node tests/gen-stubs.js

import QtQuick

Item {
  property string label: ""
  property string description: ""
  property bool checked: false
  property bool hasCursor: false
  property bool rounded: false
  property color foreground: "transparent"
  property color accent: "transparent"
  property string fontFamily: ""
  property real titleSize: 0
  property real descriptionSize: 0
  signal clicked()
  signal hovered(bool isHovered)

  implicitWidth: 120
  implicitHeight: 28
}
