// GENERATED by tests/gen-stubs.js from /usr/share/omarchy/shell/Ui/WidgetButton.qml — do not edit.
//
// Offscreen stand-in so the QML suite runs with no shell. Only the root
// object's declaration NAMES matter; the bodies are deliberately empty.
// Regenerate with: node tests/gen-stubs.js

import QtQuick

Item {
  property var bar: undefined
  property string text: ""
  property string fontFamily: ""
  property real fontSize: 0
  property color foreground: "transparent"
  property color activeColor: "transparent"
  property bool active: false
  property real horizontalMargin: 0
  property real verticalPadding: 0
  property real fixedWidth: 0
  property real fixedHeight: 0
  property real textRotation: 0
  property bool keepSpace: false
  property bool dimmed: false
  property bool concealed: false
  property bool interactive: false
  property bool pressable: false
  property bool useActiveColor: false
  property bool maintainIndicatorReveal: false
  property bool labelVisible: false
  property bool hasVisualContent: false
  property var revealHost: undefined
  property string tooltipText: ""
  property var registeredBar: undefined
  signal pressed(int button)
  signal wheelMoved(int delta)
  function triggerPress(button) { return undefined }
  function hideOwnTooltip() { return undefined }
  function syncClickRegistration() { return undefined }
  property bool vertical: false
  property int barSize: 0
  property real scaledHorizontalMargin: 0
  property real scaledVerticalPadding: 0
  property bool tooltipHovered: false
  property real labelWidth: 0

  implicitWidth: 120
  implicitHeight: 28
}
