// GENERATED by tests/gen-component-load.js — do not edit.
// Regenerate with: node tests/gen-component-load.js

import QtQuick
import QtTest

// Every component the QML engine can compile here, compiled once.
//
// This is the gate that catches the class of bug qmllint reports only as a
// Warning and that no other test can see: a syntax error, an assignment to a
// property the type does not have, or a component that references itself
// ("X is instantiated recursively"). All three make the engine refuse the file,
// and because components nest, one bad file silently takes out everything above
// it — a single bad `anchors` on a PopupCard inside StatusLine took out ChatView
// and with it the whole chat surface, and it reached the live shell first.
//
// COMPILE, not instantiate. Qt.createComponent reports exactly the errors that
// belong to the file itself and yields errorString() — the engine's own
// diagnostic. Instantiating would additionally fail on every unset
// `required property`, which is a fact about the caller, not the component.
//
// Excluded, transitively, because Quickshell's QML plugin is statically linked
// into the quickshell binary and unavailable to qmltestrunner:
//   components/FilePicker.qml  (imports Quickshell)
//   components/FilePreview.qml  (imports Quickshell)
//   components/FilesPane.qml  (imports Quickshell)
Item {
  id: harness
  width: 400
  height: 300

  readonly property var componentPaths: [
    "../../components/ApprovalStrip.qml",
    "../../components/AskUserStrip.qml",
    "../../components/AuthBanner.qml",
    "../../components/ChatInput.qml",
    "../../components/ChatView.qml",
    "../../components/CodeBlock.qml",
    "../../components/ContinuousVoiceBar.qml",
    "../../components/ConversationActionBar.qml",
    "../../components/ConversationRow.qml",
    "../../components/FileTree.qml",
    "../../components/FolderTree.qml",
    "../../components/GitPane.qml",
    "../../components/MarkdownBlock.qml",
    "../../components/McpStatusRow.qml",
    "../../components/MessageList.qml",
    "../../components/MicButton.qml",
    "../../components/NotebookPane.qml",
    "../../components/OpenScadPage.qml",
    "../../components/PiUIChrome.qml",
    "../../components/PiUIModal.qml",
    "../../components/PiUINode.qml",
    "../../components/PlanStrip.qml",
    "../../components/QueuePanel.qml",
    "../../components/RetryBanner.qml",
    "../../components/SchedulerForm.qml",
    "../../components/SchedulerPage.qml",
    "../../components/SchedulerTaskRow.qml",
    "../../components/SettingsPage.qml",
    "../../components/Sidebar.qml",
    "../../components/StatusLine.qml",
    "../../components/SystemMessageRow.qml",
    "../../components/TaskNotificationRow.qml",
    "../../components/ThinkingBlock.qml",
    "../../components/ToolCard.qml",
    "../../components/TtsIndicator.qml",
    "../../components/VoiceSettings.qml",
    "../../components/settings/AboutSettings.qml",
    "../../components/settings/AiModelSettings.qml",
    "../../components/settings/AppearanceSettings.qml",
    "../../components/settings/DiscordSettings.qml",
    "../../components/settings/GeneralSettings.qml",
    "../../components/settings/KnowledgeSettings.qml",
    "../../components/settings/MacrosSettings.qml",
    "../../components/settings/McpServerSettings.qml",
    "../../components/settings/NotificationConfigGrid.qml",
    "../../components/settings/OpenSCADSettings.qml",
    "../../components/settings/QuickChatSettings.qml",
    "../../components/settings/SettingDefRow.qml",
    "../../components/settings/SettingsSidebar.qml",
    "../../components/settings/ShortcutSettings.qml",
    "../../components/settings/StorageSettings.qml",
    "../../components/settings/ToolsSettings.qml",
    "../../components/settings/WebServerSettings.qml"
  ]

  TestCase {
    name: "ComponentCompile"
    when: windowShown

    function test_compiles_data() {
      var rows = []
      for (var i = 0; i < harness.componentPaths.length; i++) {
        rows.push({ tag: harness.componentPaths[i], path: harness.componentPaths[i] })
      }
      return rows
    }

    function test_compiles(row) {
      var c = Qt.createComponent(row.path, Component.PreferSynchronous)
      verify(c.status !== Component.Loading, row.path + " still loading")
      verify(c.status !== Component.Error, row.path + " -> " + c.errorString())
      compare(c.status, Component.Ready, row.path + " -> " + c.errorString())
    }
  }
}
